[toolchain]
channel = "1.92.0"
profile = "minimal"
components = ["rustfmt", "clippy"]
targets = [
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "i686-pc-windows-gnu",
  "x86_64-pc-windows-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-unknown-freebsd",
  "x86_64-unknown-netbsd"
]